version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev
    environment:
      KC_FEATURES: token-exchange
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_SCHEMA: auth
      KC_DB_POOL_INITIAL_SIZE: 2
      KC_DB_POOL_MAX_SIZE: 10
      # Increase the timeout slightly so background tasks don't give up so fast
      KC_DB_POOL_MAX_LIFETIME_QUANTA: 30000
      KC_TRANSACTION_XA_ENABLED: "false"

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_HTTP_PORT: 8080

      KC_HOSTNAME: https://auth.stackview.me
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      # This ensures the admin console works over HTTPS
      KC_HOSTNAME_ADMIN: https://auth.stackview.me

      TZ: ${TZ}
    volumes:
      - ./dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-theme-for-kc-all-other-versions.jar
      # - ./.auth:/opt/keycloak/themes
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
networks:
  mynet:
    external: true